version: '3'
services:
  server:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    ports:
      - "3001:3001"
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - "80:80"
