version: '3'
services:
  server:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    ports:
      - "3001:3001"
    command: yarn dev:watch
    volumes:
     - ./backend:/usr/src/backend
     - ./shared:/usr/src/shared
     - /usr/src/backend/node_modules
